### ISSUE TITLE
Glows

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft-CoreMod#3]
If you take two right or two left Hand Glows in the Ring slots no message dissapears.

**Comment by Namikon** [comment]
is it really required to display a message that you cannot use 2 left, or 2 right gloves? It's not a big deal, but I'd like to challenge the peoples common sense a bit... :P

**Comment by Dream-Master** [comment]
No big deal. So close it if you want.

**Comment by Namikon** [comment]
Closed with "Not an issue"
